# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karthik K
email: karthik@skcript.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, insights, top of my mind thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imkarthikk.com" # the base hostname & protocol for your site
twitter_username: imkarthikk
permalink: /:categories/:title
# Build settings
markdown: kramdown
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "readme.md"
  - "config.rb"
  - "Rakefile"
  - "s3_website.yml"
  - "run"
  - "push.sh"