# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Allt - Official User Guides
email: friends@skcript.com
description: > # this means to ignore newlines until "baseurl:"
  All the guides, resources, use cases and contact information you need for Allt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guides.allt.in" # the base hostname & protocol for your site
twitter_username: AlltHQ
permalink: /:categories/:title
# Build settings
markdown: kramdown
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "readme.md"
  - "config.rb"
  - "Rakefile"
  - "s3_website.yml"
  - "run"
  - "push.sh"